# Generated by Django 2.1.2 on 2018-10-11 18:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulls_and_cows', '0003_auto_20181011_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerGame',
            fields=[
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bulls_and_cows.Game')),
                ('available_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
            ],
        ),
    ]
